project_name: k8s-lab
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/run-k8s-lab/main.go
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
